name: Deploy static
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397570188272:role/github-oidc-deploy
          aws-region: us-east-1
      - run: aws s3 sync dist/ s3://kyle-white.com --delete
      - run: aws cloudfront create-invalidation --distribution-id E1LA57KS9MHIPN --paths "/*"